# for pgsql
development:
  adapter: postgresql
  encoding: utf8
  database: omoto_dev
  username: ippei
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: omoto_test
  username: ippei
  pool: 5
  timeout: 5000

